-- TI GADGET ZONE FINAL MASTER FIX v2
-- Safe migration: does not delete products/orders. Run once in Supabase SQL Editor.
create extension if not exists pgcrypto;
alter table public.settings add column if not exists dhaka_city_delivery numeric(10,2);
alter table public.settings add column if not exists dhaka_suburban_delivery numeric(10,2);
alter table public.settings add column if not exists whatsapp_number text;
update public.settings set dhaka_city_delivery=coalesce(dhaka_city_delivery,dhaka_delivery,60), dhaka_suburban_delivery=coalesce(dhaka_suburban_delivery,80), whatsapp_number=coalesce(nullif(trim(whatsapp_number),''),'01919889430') where id=true;
alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists phone text;
alter table public.orders add column if not exists full_address text;
alter table public.orders add column if not exists delivery_area text;
alter table public.orders add column if not exists payment_sender_phone text;
alter table public.order_items add column if not exists purchase_price numeric(12,2) default 0;
update public.order_items oi set purchase_price=coalesce(nullif(oi.purchase_price,0),(select pv.purchase_price from public.product_variants pv where pv.id=oi.variant_id),(select p.purchase_price from public.products p where p.id=oi.product_id),0);
alter table public.orders alter column customer_phone drop not null;
alter table public.orders alter column phone set default '';
update public.orders set delivery_area=case when area_type='dhaka' then 'dhaka_city' when area_type='outside' then 'outside' else area_type end where delivery_area is null or trim(delivery_area)='';
drop trigger if exists trg_fix_order_item_purchase_price on public.order_items; drop function if exists public.fix_order_item_purchase_price();
create or replace function public.sync_order_address_fields() returns trigger language plpgsql as $$ begin if nullif(trim(coalesce(new.full_address,'')),'') is null then new.full_address:=nullif(trim(coalesce(new.address,'')),''); end if; if nullif(trim(coalesce(new.address,'')),'') is null then new.address:=nullif(trim(coalesce(new.full_address,'')),''); end if; return new; end;$$;
drop trigger if exists trg_sync_order_address_fields on public.orders; create trigger trg_sync_order_address_fields before insert or update on public.orders for each row execute function public.sync_order_address_fields();
drop function if exists public.create_order_v2(text,text,text,text,text,text,text,text,text,jsonb);
drop function if exists public.create_order_v2(text,text,text,text,text,text,text,text,text,text,jsonb);
create or replace function public.create_order_v2(p_customer_name text,p_phone text,p_district text,p_thana text,p_address text,p_area_type text,p_payment_method text,p_payment_txn_id text,p_payment_sender_phone text,p_note text,p_items jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_order_id uuid; v_order_number text; v_subtotal numeric:=0; v_delivery numeric:=0; v_total numeric:=0; v_item jsonb; v_product public.products%rowtype; v_variant public.product_variants%rowtype; v_qty integer; v_unit numeric; v_cost numeric; v_color text;
begin
if trim(coalesce(p_customer_name,''))='' or trim(coalesce(p_phone,''))='' or trim(coalesce(p_district,''))='' or trim(coalesce(p_thana,''))='' or trim(coalesce(p_address,''))='' then raise exception 'Customer information is required'; end if;
if p_area_type not in ('dhaka_city','dhaka_suburban','outside','dhaka') then raise exception 'Invalid delivery area'; end if;
if p_payment_method not in ('cod','bkash','nagad') then raise exception 'Invalid payment method'; end if;
if p_payment_method in ('bkash','nagad') and (nullif(trim(coalesce(p_payment_txn_id,'')),'') is null or nullif(trim(coalesce(p_payment_sender_phone,'')),'') is null) then raise exception 'Send Money number and Transaction ID are required for bKash/Nagad'; end if;
if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Cart is empty'; end if;
select case when p_area_type in ('dhaka_city','dhaka') then coalesce(dhaka_city_delivery,dhaka_delivery,0) when p_area_type='dhaka_suburban' then coalesce(dhaka_suburban_delivery,80) else coalesce(outside_delivery,0) end into v_delivery from public.settings where id=true limit 1; v_delivery:=coalesce(v_delivery,0);
for v_item in select * from jsonb_array_elements(p_items) loop
v_qty:=greatest(1,coalesce((v_item->>'quantity')::integer,1)); select * into v_product from public.products where id=(v_item->>'product_id')::uuid and active=true for update; if not found then raise exception 'Product unavailable'; end if; v_unit:=v_product.selling_price; v_color:=null;
if coalesce(v_item->>'variant_id','')<>'' then select * into v_variant from public.product_variants where id=(v_item->>'variant_id')::uuid and product_id=v_product.id for update; if not found then raise exception 'Color option unavailable'; end if; if v_variant.stock<v_qty then raise exception 'Not enough stock for %',coalesce(v_variant.color_name,'selected color'); end if; v_unit:=coalesce(v_variant.selling_price,v_unit); v_color:=v_variant.color_name; update public.product_variants set stock=stock-v_qty where id=v_variant.id; else if v_product.stock<v_qty then raise exception 'Not enough stock for %',v_product.name; end if; update public.products set stock=stock-v_qty,updated_at=now() where id=v_product.id; end if; v_subtotal:=v_subtotal+v_unit*v_qty; end loop;
v_total:=v_subtotal+v_delivery; v_order_number:='TIGZ-'||to_char(now(),'YYMMDDHH24MISS')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,5));
insert into public.orders(order_number,customer_name,phone,customer_phone,district,thana,address,full_address,area_type,delivery_area,payment_method,payment_txn_id,payment_sender_phone,subtotal,delivery_charge,total,note) values(v_order_number,trim(p_customer_name),trim(p_phone),trim(p_phone),trim(p_district),trim(p_thana),trim(p_address),trim(p_address),case when p_area_type='dhaka' then 'dhaka_city' else p_area_type end,case when p_area_type='dhaka' then 'dhaka_city' else p_area_type end,p_payment_method,nullif(trim(coalesce(p_payment_txn_id,'')),''),nullif(trim(coalesce(p_payment_sender_phone,'')),''),v_subtotal,v_delivery,v_total,coalesce(p_note,'')) returning id into v_order_id;
for v_item in select * from jsonb_array_elements(p_items) loop
v_qty:=greatest(1,coalesce((v_item->>'quantity')::integer,1)); select * into v_product from public.products where id=(v_item->>'product_id')::uuid; v_unit:=v_product.selling_price; v_cost:=coalesce(v_product.purchase_price,0); v_color:=null;
if coalesce(v_item->>'variant_id','')<>'' then select * into v_variant from public.product_variants where id=(v_item->>'variant_id')::uuid; v_unit:=coalesce(v_variant.selling_price,v_unit); v_cost:=coalesce(v_variant.purchase_price,v_cost); v_color:=v_variant.color_name; end if;
insert into public.order_items(order_id,product_id,variant_id,product_name,color_name,quantity,unit_price,purchase_price,discount,total_price) values(v_order_id,v_product.id,nullif(v_item->>'variant_id','')::uuid,v_product.name,v_color,v_qty,v_unit,v_cost,0,v_unit*v_qty); end loop;
return jsonb_build_object('id',v_order_id,'order_number',v_order_number,'subtotal',v_subtotal,'delivery_charge',v_delivery,'total',v_total); end;$$;
grant execute on function public.create_order_v2(text,text,text,text,text,text,text,text,text,text,jsonb) to anon,authenticated;
create or replace function public.create_order_v2(p_customer_name text,p_phone text,p_district text,p_thana text,p_address text,p_area_type text,p_payment_method text,p_payment_txn_id text,p_note text,p_items jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ begin return public.create_order_v2(p_customer_name,p_phone,p_district,p_thana,p_address,p_area_type,p_payment_method,p_payment_txn_id,null,p_note,p_items); end;$$;
grant execute on function public.create_order_v2(text,text,text,text,text,text,text,text,text,jsonb) to anon,authenticated;
create or replace function public.tigz_normalize_phone(p text) returns text language plpgsql immutable as $$ declare d text; begin d:=regexp_replace(coalesce(p,''),'[^0-9]','','g'); if d like '8801%' then d:='0'||substr(d,4); end if; if d like '801%' then d:='0'||substr(d,3); end if; return d; end;$$;
drop function if exists public.track_order(text,text);
create or replace function public.track_order(p_order_number text,p_phone text) returns jsonb language plpgsql security definer set search_path=public as $$ declare r jsonb; begin select jsonb_build_object('order_number',o.order_number,'status',o.status,'created_at',o.created_at,'phone',coalesce(nullif(trim(o.phone),''),nullif(trim(o.customer_phone),'')),'payment_method',o.payment_method,'payment_sender_phone',o.payment_sender_phone,'payment_txn_id',o.payment_txn_id,'delivery_area',o.delivery_area,'delivery_charge',coalesce(o.delivery_charge,0),'total',coalesce(o.total,o.total_amount,0),'items',coalesce((select jsonb_agg(jsonb_build_object('product_name',i.product_name,'color_name',i.color_name,'quantity',i.quantity,'unit_price',coalesce(i.unit_price,0),'discount',coalesce(i.discount,0),'total_price',coalesce(i.total_price,0))) from public.order_items i where i.order_id=o.id),'[]'::jsonb)) into r from public.orders o where trim(o.order_number)=trim(p_order_number) and public.tigz_normalize_phone(coalesce(nullif(trim(o.phone),''),nullif(trim(o.customer_phone),'')))=public.tigz_normalize_phone(p_phone); return r; end;$$;
grant execute on function public.track_order(text,text) to anon,authenticated;
drop function if exists public.track_orders_by_phone(text);
create or replace function public.track_orders_by_phone(p_phone text) returns jsonb language plpgsql security definer set search_path=public as $$ declare r jsonb; begin select coalesce(jsonb_agg(jsonb_build_object('order_number',o.order_number,'status',o.status,'status_label',case o.status when 'pending' then 'অপেক্ষমাণ' when 'confirmed' then 'কনফার্মড' when 'processing' then 'প্রসেসিং' when 'shipped' then 'পাঠানো হয়েছে' when 'delivered' then 'ডেলিভার্ড' when 'cancelled' then 'বাতিল' when 'returned' then 'রিটার্ন' else o.status end,'created_at',o.created_at,'phone',coalesce(nullif(trim(o.phone),''),nullif(trim(o.customer_phone),'')),'total',coalesce(o.total,o.total_amount,0),'item_summary',coalesce((select string_agg(coalesce(i.product_name,'Product')||' × '||i.quantity::text,', ' order by i.id) from public.order_items i where i.order_id=o.id),'Order')) order by o.created_at desc),'[]'::jsonb) into r from public.orders o where public.tigz_normalize_phone(coalesce(nullif(trim(o.phone),''),nullif(trim(o.customer_phone),'')))=public.tigz_normalize_phone(p_phone); return r; end;$$;
grant execute on function public.track_orders_by_phone(text) to anon,authenticated;
notify pgrst,'reload schema';
